from S1E7 import Baratheon, Lannister
Robert = Baratheon("Robert")
print(Robert.__dict__)
print('-----------------------')
print(Robert.__str__)
print('-----------------------')
print(Robert.__repr__)
print('-----------------------')
print(Robert.is_alive)
print('-----------------------')
Robert.die()
print(Robert.is_alive)
print('-----------------------')
print(Robert.__doc__)
print('-----------------------')
Cersei = Lannister("Cersei")
print(Cersei.__dict__)
print('-----------------------')
print(Cersei.__str__)
print('-----------------------')
print(Cersei.is_alive)
print('-----------------------')
Jaine = Lannister.create_lannister("Jaine", True)
print(
    f"Name : {Jaine.first_name, type(Jaine).__name__}, Alive : {Jaine.is_alive}")
